import env from '../env'

// Wallet
export const PRIVATE_KEY = env.PRIVATE_KEY

// Connection
export const NETWORK = 'mainnet-beta'
export const COMMITMENT_LEVEL = env.COMMITMENT_LEVEL
export const RPC_ENDPOINT = env.RPC_ENDPOINT
export const RPC_WEBSOCKET_ENDPOINT = env.RPC_WEBSOCKET_ENDPOINT

// Bot
export const LOG_LEVEL = env.LOG_LEVEL
export const ONE_TOKEN_AT_A_TIME = env.ONE_TOKEN_AT_A_TIME
export const COMPUTE_UNIT_LIMIT = env.COMPUTE_UNIT_LIMIT
export const COMPUTE_UNIT_PRICE = env.COMPUTE_UNIT_PRICE
export const PRE_LOAD_EXISTING_MARKETS = env.PRE_LOAD_EXISTING_MARKETS
export const CACHE_NEW_MARKETS = env.CACHE_NEW_MARKETS
export const TRANSACTION_EXECUTOR = env.TRANSACTION_EXECUTOR
export const CUSTOM_FEE = env.CUSTOM_FEE

// Buy
export const AUTO_BUY_DELAY = env.AUTO_BUY_DELAY
export const QUOTE_MINT = env.QUOTE_MINT
export const QUOTE_AMOUNT = env.QUOTE_AMOUNT
export const MAX_BUY_RETRIES = env.MAX_BUY_RETRIES
export const BUY_SLIPPAGE = env.BUY_SLIPPAGE

// Sell
export const AUTO_SELL = env.AUTO_SELL
export const AUTO_SELL_DELAY = env.AUTO_SELL
export const MAX_SELL_RETRIES = env.MAX_SELL_RETRIES
export const TAKE_PROFIT = env.MAX_SELL_RETRIES
export const STOP_LOSS = env.MAX_SELL_RETRIES
export const PRICE_CHECK_INTERVAL = env.PRICE_CHECK_INTERVAL
export const PRICE_CHECK_DURATION = env.PRICE_CHECK_DURATION
export const SELL_SLIPPAGE = env.SELL_SLIPPAGE

// Filters
export const FILTER_CHECK_INTERVAL = env.FILTER_CHECK_INTERVAL
export const FILTER_CHECK_DURATION = env.FILTER_CHECK_DURATION
export const CONSECUTIVE_FILTER_MATCHES = env.FILTER_CHECK_DURATION
export const CHECK_IF_MUTABLE = env.CHECK_IF_MUTABLE
export const CHECK_IF_SOCIALS = env.CHECK_IF_SOCIALS
export const CHECK_IF_MINT_IS_RENOUNCED = env.CHECK_IF_MINT_IS_RENOUNCED
export const CHECK_IF_FREEZABLE = env.CHECK_IF_FREEZABLE
export const CHECK_IF_BURNED = env.CHECK_IF_BURNED
export const MIN_POOL_SIZE = env.MIN_POOL_SIZE
export const MAX_POOL_SIZE = env.MAX_POOL_SIZE
export const USE_SNIPE_LIST = env.USE_SNIPE_LIST
export const SNIPE_LIST_REFRESH_INTERVAL = env.SNIPE_LIST_REFRESH_INTERVAL
